### ISSUE TITLE
Issue with natura?

### ISSUE THREAD

**Issue by BullerEX** [djpadbit/Sound-Physics#12]
I have natura installed on my mod pack and the other mod that help u get the log when some error happends this is it:
not sure if Im doing well by posting just cause the mod told me to but you can yell at me if you want
https://paste.dimdev.org/ubujosifac.mccrash

**Comment by djpadbit** [comment]
What were you doing when the crash came up ? Were there any entities from natura (or other mods) that made sound ?

**Comment by djpadbit** [comment]
[Sound-Physics-1.12.2.zip](https://github.com/djpadbit/Sound-Physics/files/3448421/Sound-Physics-1.12.2.zip). The issue is fixed in the next release but in the meantime you can use this build.

**Comment by BullerEX** [comment]
I was exiting the nether portal and yes there was some stairs from natura, still not sure abt it

**Comment by djpadbit** [comment]
The issue should be fixed in the build provided in my last message, did you try it out ?
