### ISSUE TITLE
There is no vehicle sound compatible with MrCrayfish's Vehicle Mod

### ISSUE THREAD

**Issue by Kino0208** [djpadbit/Sound-Physics#52]
After installing Sound-Physics-1.12.2-1.0.10-1.jar, the vehicle in my MrCrayfish's Vehicle Mod-0.44.1-1.12.2 cannot emit engine sound normally! But my friend can hear the sound of my vehicle, I can't hear it myself! I'm sorry I don't speak English, I used machine translation of this paragraph (

在安装了Sound-Physics-1.12.2-1.0.10-1.jar之后，我的MrCrayfish's Vehicle Mod-0.44.1-1.12.2里的载具无法正常的发出引擎声！ 但是我的朋友可以听到我的载具声，我自己听不到！很抱歉我不会英语，这段话是我用机器翻译出来的（

**Comment by djpadbit** [comment]
I'm going to look into it

**Comment by Kino0208** [comment]
> 我会调查一下

Thanks!

**Comment by djpadbit** [comment]
It should be fixed now,  [Here](https://github.com/djpadbit/Sound-Physics/files/5758138/Sound-Physics-1.12.2-1.0.10-1.zip)'s a build with the changes. I'm sorry for the late reply though.

**Comment by Kino0208** [comment]
> 它现在应该修复，[这里是](https://github.com/djpadbit/Sound-Physics/files/5758138/Sound-Physics-1.12.2-1.0.10-1.zip)一个与更改的生成。不过， 我很抱歉回复太迟了。

It's ok! thank you very much! This is a surprise!

**Comment by skedgywasedgy** [comment]
This issue still exists in 1.16.3. I'd fix it myself but the code around where the fix was implemented is commented out in the 1.16.3 branch which gives the impression touching any of that will probably cause more problems.
